# Generated by Django 5.0.3 on 2024-06-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewFeedbackSystem', '0003_alter_bewertung_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='bewertung',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='bewertung',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='ReviewFeedbackSystem.user'),
        ),
    ]
