# Generated by Django 5.0.3 on 2024-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewFeedbackSystem', '0005_alter_bewertung_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewertung',
            name='bewertung',
        ),
        migrations.AddField(
            model_name='bewertung',
            name='bewertung_ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='bewertung',
            name='bewertung_essen',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='bewertung',
            name='bewertung_gesamt',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='bewertung',
            name='bewertung_service',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
