# Generated by Django 5.0.6 on 2024-06-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationManagement', '0005_reservation_anmerkungen'),
        ('RestaurantManagement', '0005_table_count'),
        ('ReviewFeedbackSystem', '0006_remove_bewertung_bewertung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='RestaurantManagement.restaurant'),
        ),
        migrations.AlterField(
            model_name='bewertung',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bewertung',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='ReservationManagement.reservation'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
