# Generated by Django 5.0.3 on 2024-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewFeedbackSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertung', models.PositiveSmallIntegerField(choices=[(1, 'Mangelhaft'), (2, 'Befriedigend'), (3, 'Gut'), (4, 'Sehr gut'), (5, 'Ausgezeichnet')], default=3)),
                ('kommentar', models.TextField()),
            ],
        ),
    ]
