# Generated by Django 5.0.3 on 2024-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewFeedbackSystem', '0002_bewertung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='bewertung',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
