# Generated by Django 5.0.3 on 2024-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewFeedbackSystem', '0002_bewertung'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewertung',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
