# Generated by Django 5.0.3 on 2024-05-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewFeedbackSystem', '0003_bewertung_erstellt_am'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewertung',
            name='erstellt_am',
        ),
    ]
